server:
  port: 8888
spring:
  application:
    name: sc-config-server
  profiles:
    active: native
  cloud:
     config:
       server:
           native:
              searchLocations:  classpath:configs/